# Generated by Django 2.2.1 on 2019-05-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction_API', '0002_auto_20190506_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image_url',
            field=models.FileField(upload_to=''),
        ),
    ]
