# Generated by Django 2.2.1 on 2019-05-22 15:29

import Auction_API.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction_API', '0003_auto_20190522_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image_url',
            field=models.FileField(upload_to=Auction_API.models.upload_image_path),
        ),
    ]
